### ISSUE TITLE
FFT Value Interpretation and Complex Numbers

### ISSUE THREAD

**Issue by madsami** [sunkin351/FmodAudio#7] opened 2022-01-05 08:50 UTC
In many cases we want to take the raw values from the object _ParameterFFT* fftData = (ParameterFFT*) ptr;_ and extrapolate them into another format. I didn't feel that it is clear if the values from this call already come processed using Complex number class, or if it has to be done manually.

In the case of manually, the current design recommends we first store the value in the base Complex class (double), then use that as a parameter for the Fmod_Complex (float).
When we get the FFT spectrum using _floatspectrum = fftData->GetSpectrum(channel);_ it's in float, however since Fmod_Complex is made to work with Base Complex, no constructor taking the raw float values, there are some extra operations that probably can be bypassed if the Fmod_Complex class receive some updates such as constructor for taking the float, method for getting Magnitude etc.

Or, am I totally misunderstanding the use of this interface?

**Comment by sunkin351** [comment] 2022-01-06 21:11
What calculation are you trying to do exactly? A small example would be appreciated.

**Comment by madsami** [comment] 2022-01-13 16:50
I apologize, it might have just been my confusion.
Many tutorials using FFT show that raw output values have to be made into Complex numbers in order to calculate the magnitude, and then convert to decibels, and it was unclear to me if Fmod's FFT needed the same, thus I pointed out the issue that in the current implementation of FmodAudio, in order to transform FFTdata[i] which is a float into FmodComplex[i], also float, but does not accept float parameters, only the base class Complex, which is in double - making for some extra calculations, considering this is something often done in real-time, it's a wasted operation if FmodComplex could be constructed using float parameters directly instead of only accepting the base Complex as a constructor parameter.

**Comment by sunkin351** [comment] 2022-01-13 18:07
I just remembered, `FmodComplex` is just for API completeness, if you want to do proper calculations with complex numbers, `System.Numerics.Complex` is what you should use, especially if you don't need to pass complex numbers to the FMOD api.

PS. float to double conversion is quite cheap.

**Comment by sunkin351** [comment] 2022-01-21 08:16
I'm guessing the issue is resolved, so I'm closing this.

**Closed as completed by sunkin351** 2022-01-21 08:16 UTC
